import { AmbienceType, SoundCategory } from "./enums";
import type { SoundTrack } from "./types/types";

function publicAsset(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}

export const soundTracks: SoundTrack[] = [
  {
    category: SoundCategory.Nature,
    id: AmbienceType.Campfire,
    label: "Campfire",
    src: publicAsset("sounds/nature/campfire.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.Droplets,
    label: "Droplets",
    src: publicAsset("sounds/nature/droplets.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.HowlingWind,
    label: "Howling wind",
    src: publicAsset("sounds/nature/howling-wind.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.Jungle,
    label: "Jungle",
    src: publicAsset("sounds/nature/jungle.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.River,
    label: "River",
    src: publicAsset("sounds/nature/river.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.WalkInSnow,
    label: "Walk in snow",
    src: publicAsset("sounds/nature/walk-in-snow.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.WalkOnGravel,
    label: "Walk on gravel",
    src: publicAsset("sounds/nature/walk-on-gravel.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.WalkOnLeaves,
    label: "Walk on leaves",
    src: publicAsset("sounds/nature/walk-on-leaves.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.Waterfall,
    label: "Waterfall",
    src: publicAsset("sounds/nature/waterfall.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.Waves,
    label: "Waves",
    src: publicAsset("sounds/nature/waves.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.Wind,
    label: "Wind",
    src: publicAsset("sounds/nature/wind.mp3"),
  },
  {
    category: SoundCategory.Nature,
    id: AmbienceType.WindInTrees,
    label: "Wind in trees",
    src: publicAsset("sounds/nature/wind-in-trees.mp3"),
  },
  {
    category: SoundCategory.Rain,
    id: AmbienceType.HeavyRain,
    label: "Heavy rain",
    src: publicAsset("sounds/rain/heavy-rain.mp3"),
  },
  {
    category: SoundCategory.Rain,
    id: AmbienceType.LightRain,
    label: "Light rain",
    src: publicAsset("sounds/rain/light-rain.mp3"),
  },
  {
    category: SoundCategory.Rain,
    id: AmbienceType.RainOnCarRoof,
    label: "Rain on car roof",
    src: publicAsset("sounds/rain/rain-on-car-roof.mp3"),
  },
  {
    category: SoundCategory.Rain,
    id: AmbienceType.RainOnLeaves,
    label: "Rain on leaves",
    src: publicAsset("sounds/rain/rain-on-leaves.mp3"),
  },
  {
    category: SoundCategory.Rain,
    id: AmbienceType.RainOnTent,
    label: "Rain on tent",
    src: publicAsset("sounds/rain/rain-on-tent.mp3"),
  },
  {
    category: SoundCategory.Rain,
    id: AmbienceType.RainOnWindow,
    label: "Rain on window",
    src: publicAsset("sounds/rain/rain-on-window.mp3"),
  },
  {
    category: SoundCategory.Rain,
    id: AmbienceType.Thunder,
    label: "Thunder",
    src: publicAsset("sounds/rain/thunder.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Beehive,
    label: "Beehive",
    src: publicAsset("sounds/animals/beehive.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Birds,
    label: "Birds",
    src: publicAsset("sounds/animals/birds.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.CatPurring,
    label: "Cat purring",
    src: publicAsset("sounds/animals/cat-purring.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Chickens,
    label: "Chickens",
    src: publicAsset("sounds/animals/chickens.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Cows,
    label: "Cows",
    src: publicAsset("sounds/animals/cows.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Crickets,
    label: "Crickets",
    src: publicAsset("sounds/animals/crickets.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Crows,
    label: "Crows",
    src: publicAsset("sounds/animals/crows.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.DogBarking,
    label: "Dog barking",
    src: publicAsset("sounds/animals/dog-barking.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Frog,
    label: "Frog",
    src: publicAsset("sounds/animals/frog.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.HorseGallop,
    label: "Horse gallop",
    src: publicAsset("sounds/animals/horse-gallop.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Owl,
    label: "Owl",
    src: publicAsset("sounds/animals/owl.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Seagulls,
    label: "Seagulls",
    src: publicAsset("sounds/animals/seagulls.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Sheep,
    label: "Sheep",
    src: publicAsset("sounds/animals/sheep.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Whale,
    label: "Whale",
    src: publicAsset("sounds/animals/whale.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Wolf,
    label: "Wolf",
    src: publicAsset("sounds/animals/wolf.mp3"),
  },
  {
    category: SoundCategory.Animals,
    id: AmbienceType.Woodpecker,
    label: "Woodpecker",
    src: publicAsset("sounds/animals/woodpecker.mp3"),
  },
  {
    category: SoundCategory.Urban,
    id: AmbienceType.Crowd,
    label: "Crowd",
    src: publicAsset("sounds/urban/crowd.mp3"),
  },
  {
    category: SoundCategory.Places,
    id: AmbienceType.Church,
    label: "Church",
    src: publicAsset("sounds/places/church.mp3"),
  },
  {
    category: SoundCategory.Places,
    id: AmbienceType.CrowdedBar,
    label: "Crowded bar",
    src: publicAsset("sounds/places/crowded-bar.mp3"),
  },
  {
    category: SoundCategory.Places,
    id: AmbienceType.Library,
    label: "Library",
    src: publicAsset("sounds/places/library.mp3"),
  },
  {
    category: SoundCategory.Places,
    id: AmbienceType.NightVillage,
    label: "Night village",
    src: publicAsset("sounds/places/night-village.mp3"),
  },
  {
    category: SoundCategory.Places,
    id: AmbienceType.Restaurant,
    label: "Restaurant",
    src: publicAsset("sounds/places/restaurant.mp3"),
  },
  {
    category: SoundCategory.Places,
    id: AmbienceType.Temple,
    label: "Temple",
    src: publicAsset("sounds/places/temple.mp3"),
  },
  {
    category: SoundCategory.Places,
    id: AmbienceType.Underwater,
    label: "Underwater",
    src: publicAsset("sounds/places/underwater.mp3"),
  },
  {
    category: SoundCategory.Things,
    id: AmbienceType.BoilingWater,
    label: "Boiling water",
    src: publicAsset("sounds/things/boiling-water.mp3"),
  },
  {
    category: SoundCategory.Things,
    id: AmbienceType.Bubbles,
    label: "Bubbles",
    src: publicAsset("sounds/things/bubbles.mp3"),
  },
  {
    category: SoundCategory.Things,
    id: AmbienceType.Clock,
    label: "Clock",
    src: publicAsset("sounds/things/clock.mp3"),
  },
  {
    category: SoundCategory.Things,
    id: AmbienceType.Paper,
    label: "Paper",
    src: publicAsset("sounds/things/paper.mp3"),
  },
  {
    category: SoundCategory.Things,
    id: AmbienceType.SingingBowl,
    label: "Singing bowl",
    src: publicAsset("sounds/things/singing-bowl.mp3"),
  },
  {
    category: SoundCategory.Things,
    id: AmbienceType.WindChimes,
    label: "Wind chimes",
    src: publicAsset("sounds/things/wind-chimes.mp3"),
  },
  {
    category: SoundCategory.LongAmbients,
    id: AmbienceType.CastleNight,
    label: "Castle night",
    src: publicAsset("sounds/long-ambients/castle-night.mp3"),
  },
  {
    category: SoundCategory.LongAmbients,
    id: AmbienceType.MedievalVillage,
    label: "Medieval village",
    src: publicAsset("sounds/long-ambients/medieval-village.mp3"),
  },
  {
    category: SoundCategory.LongAmbients,
    id: AmbienceType.TavernAmbience,
    label: "Tavern Ambience",
    src: publicAsset("sounds/long-ambients/tavern-ambience.mp3"),
  },
  {
    category: SoundCategory.LongAmbients,
    id: AmbienceType.VillageBell,
    label: "Village bell",
    src: publicAsset("sounds/long-ambients/village-bell.mp3"),
  },
  {
    category: SoundCategory.LongAmbients,
    id: AmbienceType.Fireplace,
    label: "Fireplace",
    src: publicAsset("sounds/long-ambients/fireplace.mp3"),
  },
];
